### ISSUE TITLE
Test Run on GPU

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#177]
Goal: Double check that the current code works on a single machine with multiple (Ampere) GPUs

**Comment by Ivan-Zhou** [comment]
This might be related to the jax version I am using. I would try reinstalling Jax for GPU specifically.

**Comment by Ivan-Zhou** [comment]
After I reinstall Jax for CUDA 11, it would now recognize GPU as the backend. 

```
>>> import jax
>>> jax.default_backend()
'gpu'
```

**Comment by Ivan-Zhou** [comment]
I consistently encountered this issue in both the NLP Cluster and GPU on GCP:

```
python examples/gpt2_example.py --config_path config/gpt2_small.yaml --trainer.checkpointer.base_path gs://levanter-checkpoints/gpt2/ --trainer.checkpointer.save_interval 60m
Traceback (most recent call last):
  File "/sailhome/ivanzhou/dev/levanter/examples/gpt2_example.py", line 12, in <module>
    import haliax as hax
  File "/sailhome/ivanzhou/dev/levanter/src/haliax/__init__.py", line 6, in <module>
    import haliax.random as random
  File "/sailhome/ivanzhou/dev/levanter/src/haliax/random.py", line 15, in <module>
    from .partitioning import auto_sharded, physical_axis_name, physical_axis_size, pspec_for_axis
  File "/sailhome/ivanzhou/dev/levanter/src/haliax/partitioning.py", line 13, in <module>
    from jax.interpreters.pxla import PartitionSpec
ImportError: cannot import name 'PartitionSpec' from 'jax.interpreters.pxla' (/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/interpreters/pxla.py)
```

'PartitionSpec' is indeed not from 'jax.interpreters.pxla' in the latest Jax code. I suspect it is a version issue.

**Comment by Ivan-Zhou** [comment]
This issue might be from the CUDA toolkit version on the nlp cluster:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sailhome/ivanzhou/dev/levanter/examples/gpt2_example.py", line 295, in <module>
    main()
  File "/sailhome/ivanzhou/dev/levanter/src/levanter/config.py", line 585, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/sailhome/ivanzhou/dev/levanter/examples/gpt2_example.py", line 85, in main
    data_key, loader_key, model_key, training_key = jrandom.split(jrandom.PRNGKey(seed), 4)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 734, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 746, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 751, in random_seed_impl_base
    return seed(seeds)
  File "/nlp/scr/ivanzhou/miniconda3/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 980, in threefry_seed
    return _threefry_seed(seed)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal   : Input file '/tmp/ivanzhou/tempfile-jagupard30.stanford.edu-c0a9f660-922442-5fd413e18fe99.cubin' newer than toolkit (118 vs 111)
```

**Comment by Ivan-Zhou** [comment]
Changed to GCP -- received the following error:

```
Traceback (most recent call last):
  File "/home/ivanzhou/levanter/examples/gpt2_example.py", line 295, in <module>
    main()
  File "/home/ivanzhou/levanter/src/levanter/config.py", line 585, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/ivanzhou/levanter/examples/gpt2_example.py", line 85, in main
    data_key, loader_key, model_key, training_key = jrandom.split(jrandom.PRNGKey(seed), 4)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/random.py", line 155, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 369, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 650, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 662, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 667, in random_seed_impl_base
    return seed(seeds)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/prng.py", line 896, in threefry_seed
    return _threefry_seed(seed)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/pjit.py", line 249, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/pjit.py", line 160, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 2647, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/pjit.py", line 1193, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/pjit.py", line 1177, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/pjit.py", line 1113, in _pjit_call_impl_python
    always_lower=False, lowering_platform=None).compile()
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2319, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2638, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/levanter/lib/python3.10/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

**Comment by dlwh** [comment]
@julian-q you saw this issue before I think? I think it's version mismatch

**Comment by dlwh** [comment]
what's the error that comes before that error? how are you installing jax?

**Comment by Ivan-Zhou** [comment]
I installed jax for GPU with this:

```
pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

This will install the latest version, which is 0.4.11. I need to use this branch to run with the latest version: https://github.com/stanford-crfm/levanter/pull/179

**Comment by dlwh** [comment]
Ok, yeah. Jax changed the instructions nad I think that you're just getting
a silent failure. Try this:

https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier

pip install --upgrade pip

# CUDA 12 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda12_pip]" -f
https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# CUDA 11 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda11_pip]" -f
https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

**Comment by Ivan-Zhou** [comment]
I think the mismatch is between Jax and cuDNN. The latest jax 0.4.11 works with CUDA 11 and cuDNN 8.6. However, in my GCP instance, I have CUDA 11.6 and cuDNN 8.2. This caused mismatch. 

Only jax 0.4.8 was compatible with cuDNN 8.2, but jax 0.4.8 won't work for our codebase. 

Therefore, a viable approach is for me to upgrade cuDNN from 8.2 to 8.6.

**Comment by Ivan-Zhou** [comment]
After switching to nvidia-ai-enterprise-vmi-1-vm image with CUDA 12, I was able to launch a training job successfully!

https://wandb.ai/stanford-mercury/levanter-examples/runs/f22i92qs?workspace=user-ivanzhou

🎉

**Comment by Ivan-Zhou** [comment]
I tested on a GCP instance with 2 A100s. Both GPUs are occupied:
![CleanShot 2023-06-04 at 16 55 15](https://github.com/stanford-crfm/levanter/assets/8097756/f8a80545-456e-43c5-9319-f3ed789fcf99)
![CleanShot 2023-06-04 at 16 57 06](https://github.com/stanford-crfm/levanter/assets/8097756/7d640bb0-767b-46c0-bf9b-a27deaf26b0e)
