### ISSUE TITLE
Gracefully handle case when there's no validation set

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#360]
RPv1 and v2 only have train set, which caused the following error. 
```
Traceback (most recent call last):
  File "/home/ivan/levanter/src/levanter/main/train_lm.py", line 186, in <module>
    levanter.config.main(main)()
  File "/home/ivan/levanter/src/levanter/config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/ivan/levanter/src/levanter/main/train_lm.py", line 103, in main
    eval_dataset = CausalLmDataset(config.data.token_seq_dataset("validation", Pos.size), Pos, KeyPos)
  File "/home/ivan/levanter/src/levanter/data/text.py", line 549, in token_seq_dataset
    cache = self.build_or_load_cache(split, monitors=monitors)
  File "/home/ivan/levanter/src/levanter/data/text.py", line 555, in build_or_load_cache
    source = self.get_shard_source(split)
  File "/home/ivan/levanter/src/levanter/data/text.py", line 476, in get_shard_source
    ds = WrappedHFDataset(self.id, split=split, name=self.name, streaming=self.stream)
  File "/home/ivan/levanter/src/levanter/data/sharded_dataset.py", line 150, in __init__
    self._shard_names = self._compute_shard_names()
  File "/home/ivan/levanter/src/levanter/data/sharded_dataset.py", line 157, in _compute_shard_names
    dataset = self._load_dataset()
  File "/home/ivan/levanter/src/levanter/data/sharded_dataset.py", line 183, in _load_dataset
    return datasets.load_dataset(self.id, split=self.split, **self.kwargs)
  File "/home/ivan/venv310/lib/python3.10/site-packages/datasets/load.py", line 1784, in load_dataset
    return builder_instance.as_streaming_dataset(split=split)
  File "/home/ivan/venv310/lib/python3.10/site-packages/datasets/builder.py", line 1271, in as_streaming_dataset
    raise ValueError(f"Bad split: {split}. Available splits: {list(splits_generators)}")
ValueError: Bad split: validation. Available splits: ['train']
```

We need to think of a way of handling this. 
1. Not set val set and skip validation loss
2. Allocate 1K train examples to val set.

**Comment by dlwh** [comment]
My preference would be to tackle this as part of #217. Basically we should go through each named source (e.g. webtext, wiki) and add a validation callback for each source that has a validation set.
