### ISSUE TITLE
ModuleNotFoundError: No module named 'test_shard_cache'

### ISSUE THREAD

**Issue by DwarKapex** [stanford-crfm/levanter#488]
Hi, all.

   I'm trying to run some unit-tests for Levanter on my machine with A100 using the following cmd:
```
pip install pytest && pytest /opt/levanter/tests
```

But I do see the following error for several tests:

```
opt/levanter/tests/test_replicated_loader.py .......                     [ 78%]
(ChunkCacheBroker pid=27992) No module named 'test_shard_cache'
(ChunkCacheBroker pid=27992) Traceback (most recent call last):
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 404, in deserialize_objects
(ChunkCacheBroker pid=27992)     obj = self._deserialize_object(data, metadata, object_ref)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 270, in _deserialize_object
(ChunkCacheBroker pid=27992)     return self._deserialize_msgpack_data(data, metadata_fields)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 225, in _deserialize_msgpack_data
(ChunkCacheBroker pid=27992)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 215, in _deserialize_pickle5_data
(ChunkCacheBroker pid=27992)     obj = pickle.loads(in_band)
(ChunkCacheBroker pid=27992) ModuleNotFoundError: No module named 'test_shard_cache'
(ChunkCacheBroker pid=27992) No module named 'test_shard_cache'
(ChunkCacheBroker pid=27992) Traceback (most recent call last):
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 404, in deserialize_objects
(ChunkCacheBroker pid=27992)     obj = self._deserialize_object(data, metadata, object_ref)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 270, in _deserialize_object
(ChunkCacheBroker pid=27992)     return self._deserialize_msgpack_data(data, metadata_fields)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 225, in _deserialize_msgpack_data
(ChunkCacheBroker pid=27992)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(ChunkCacheBroker pid=27992)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/serialization.py", line 215, in _deserialize_pickle5_data
(ChunkCacheBroker pid=27992)     obj = pickle.loads(in_band)
(ChunkCacheBroker pid=27992) ModuleNotFoundError: No module named 'test_shard_cache'
(ChunkCacheBroker pid=27992) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::lev_cache_manager::/tmp/tmplapxdrjl:ChunkCacheBroker.__init__() (pid=27992, ip=[172](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8014636750/job/21893952263?pr=575#step:8:173).17.0.2, actor_id=2f8a77b95423d34df4af6bbe01000000, repr=<levanter.data.shard_cache.ChunkCacheBroker object at 0x7f0aa83ecbb0>)
(ChunkCacheBroker pid=27992)   At least one of the input arguments for this task could not be computed:
(ChunkCacheBroker pid=27992) ray.exceptions.RaySystemError: System error: No module named 'test_shard_cache'
```

Any help with this is more then appreciated =)

**Comment by dlwh** [comment]
can you export `PYTHONPATH=/opt/levanter/tests:$PYTHONPATH`

**Comment by DwarKapex** [comment]
> can you export `PYTHONPATH=/opt/levanter/tests:$PYTHONPATH`

Yes, that helped. Thanks a lot! I will close this issue.
