### ISSUE TITLE
No accelerator found. Please run on a TPU or GPU

### ISSUE THREAD

**Issue by AdrLfv** [stanford-crfm/levanter#668]
I try to run the test on GPU but get the error "No accelerator found. Please run on a TPU or GPU."
I use the command:
`python src/levanter/main/train_lm.py --config_path config/gpt2_small.yaml`

I have an NVIDIA RTX 3060. How should I specify that I want to use it?

**Comment by dlwh** [comment]
Which version of the startup guide did you follow here https://github.com/stanford-crfm/levanter/blob/main/docs/Getting-Started-GPU.md ? How'd you install Levanter?

I haven't tested on a 3060, but I know a 3090 works so you should be ok.

**Comment by AdrLfv** [comment]
I set up the virtual environnement (virtualenv)

**Comment by dlwh** [comment]
what cuda driver version? how did you install jax? what is the exact sequence of commands you used?

**Comment by AdrLfv** [comment]
I reinstalled jax with the command `pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
but now I get 

> RuntimeError: jaxlib version 0.4.30 is newer than and incompatible with jax version 0.4.6. Please update your jax and/or jaxlib packages.

**Comment by dlwh** [comment]
they recently changed it. Try:

`pip install -U "jax[cuda12]"`

**Comment by AdrLfv** [comment]
I get 

> jaxlib version 0.4.30 is newer than and incompatible with jax version 0.4.21

, I think I should downgrade jxlib version so it's inferior to jax one according to jax' doc (https://jax.readthedocs.io/en/latest/jep/9419-jax-versioning.html)

**Comment by dlwh** [comment]
can you delete the venv and make a new one with these steps

```
git clone https://github.com/stanford-crfm/levanter.git
cd levanter
virtualenv -p python3.10 levanter_env
source levanter_env/bin/activate
pip install --upgrade "jax[cuda12]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -e .
```

instead of what you did? (JAX changed the name of the extras)

**Comment by AdrLfv** [comment]
I still have the same problem unfortunately
```
Traceback (most recent call last):
  File "C:\Users\lefev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lefev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\MIT project\levanter\src\levanter\main\train_lm.py", line 220, in <module>
    levanter.config.main(main)()
  File "D:\MIT project\levanter\src\levanter\config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "D:\MIT project\levanter\src\levanter\main\train_lm.py", line 82, in main
    levanter.initialize(config)
  File "D:\MIT project\levanter\src\levanter\trainer.py", line 796, in initialize
    trainer_config.initialize()
  File "D:\MIT project\levanter\src\levanter\trainer.py", line 636, in initialize
    raise RuntimeError("No accelerator found. Please run on a TPU or GPU.")
RuntimeError: No accelerator found. Please run on a TPU or GPU.
Traceback (most recent call last):
  File "C:\Users\lefev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lefev\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\MIT project\levanter\src\levanter\main\train_lm.py", line 220, in <module>
    levanter.config.main(main)()
  File "D:\MIT project\levanter\src\levanter\config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "D:\MIT project\levanter\src\levanter\main\train_lm.py", line 82, in main
    levanter.initialize(config)
  File "D:\MIT project\levanter\src\levanter\trainer.py", line 796, in initialize
    trainer_config.initialize()
  File "D:\MIT project\levanter\src\levanter\trainer.py", line 636, in initialize
    raise RuntimeError("No accelerator found. Please run on a TPU or GPU.")
RuntimeError: No accelerator found. Please run on a TPU or GPU.
wandb: \ 0.014 MB of 0.014 MB uploaded
wandb: Run summary:
wandb:     backend cpu
wandb: num_devices 1
wandb:   num_hosts 1
```

**Comment by dlwh** [comment]
hrm. So, this is kind of a JAX installation problem and I don't really know what to say. Can you ask in the JAX Forums (feel free to cc me), but just show that jax.devices() isn't returning a GPU (in a script)

Are you able to try the docker container?

**Comment by AdrLfv** [comment]
the command `nvidia-smi` gave me:
```
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 555.42
```
I solved the problem doing:
```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update
sudo apt-get install nvidia-driver-555
``` (you may adapt the version from Nvidia's website)
and then reboot
