### ISSUE TITLE
Regression at pip install in docker build

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#692]
I am running into this issue when launching a docker job. 

I believe it is related to https://github.com/stanford-crfm/levanter/pull/691, but I haven't found the root cause yet. 

I could pip install locally, but when I run `launch.py`, it will fail by complaining `src` does not exist. 

```
 => ERROR [4/5] RUN pip install -e '.[test]'                               8.2s
------
 > [4/5] RUN pip install -e '.[test]':
1.785 Obtaining file:///opt/levanter
1.790   Installing build dependencies: started
7.423   Installing build dependencies: finished with status 'done'
7.425   Checking if build backend supports build_editable: started
7.670   Checking if build backend supports build_editable: finished with status 'done'
7.671   Getting requirements to build editable: started
7.980   Getting requirements to build editable: finished with status 'error'
7.986   error: subprocess-exited-with-error
7.986   
7.986   × Getting requirements to build editable did not run successfully.
7.986   │ exit code: 1
7.986   ╰─> [2 lines of output]
7.986       running egg_info
7.986       error: error in 'egg_base' option: 'src' does not exist or is not a directory
7.986       [end of output]
7.986   
7.986   note: This error originates from a subprocess, and is likely not a problem with pip.
7.988 error: subprocess-exited-with-error
7.988 
7.988 × Getting requirements to build editable did not run successfully.
7.988 │ exit code: 1
7.988 ╰─> See above for output.
7.988 
7.988 note: This error originates from a subprocess, and is likely not a problem with pip.
7.993 
7.993 [notice] A new release of pip is available: 24.0 -> 24.2
7.993 [notice] To update, run: pip install --upgrade pip
------
Dockerfile.incremental:16
--------------------
  14 |     
  15 |     ADD pyproject.toml README.md /opt/levanter/
  16 | >>> RUN pip install -e '.[test]'
  17 |     ADD . /opt/levanter
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -e '.[test]'" did not complete successfully: exit code: 1
Traceback (most recent call last):
  File "/home/shared/ivanz/levanter/infra/launch.py", line 264, in <module>
    full_image_id = push_docker.push_to_gcp(
  File "/home/shared/ivanz/levanter/infra/push_docker.py", line 173, in push_to_gcp
    local_image = build_docker(docker_file=docker_file, image_name=image_name, tag=tag)
  File "/home/shared/ivanz/levanter/infra/push_docker.py", line 134, in build_docker
    _run(
  File "/home/shared/ivanz/levanter/infra/push_docker.py", line 42, in _run
    raise subprocess.CalledProcessError(exit_code, argv)
subprocess.CalledProcessError: Command '['docker', 'buildx', 'build', '--platform=linux/amd64', '-t', 'marin-ivan:1723607320', '-f', 'docker/tpu/Dockerfile.incremental', '.']' returned non-zero exit status 256.
```

**Comment by Ivan-Zhou** [comment]
If I revert the change of https://github.com/stanford-crfm/levanter/pull/691, it will succeed.

**Comment by dlwh** [comment]
ugh i can reproduce, give me a few
