### ISSUE TITLE
jax.core.pp_eqn_rules was removed in JAX v0.4.34.

### ISSUE THREAD

**Issue by hmaqboolnv** [stanford-crfm/levanter#767]
Hello,
I was trying to run gpt2_small with JAX v0.4.34 and get the following error. 

`python3 -m levanter.main.train_lm --config_path gpt2_small.yaml --trainer.train_batch_size=4 --trainer.num_train_steps=500
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/levanter/src/levanter/__init__.py", line 1, in <module>
    import levanter.checkpoint as checkpoint
  File "/opt/levanter/src/levanter/checkpoint.py", line 15, in <module>
    import equinox
  File "/usr/local/lib/python3.10/dist-packages/equinox/__init__.py", line 3, in <module>
    from . import debug as debug, internal as internal, nn as nn
  File "/usr/local/lib/python3.10/dist-packages/equinox/internal/__init__.py", line 46, in <module>
    from ._finalise_jaxpr import (
  File "/usr/local/lib/python3.10/dist-packages/equinox/internal/_finalise_jaxpr.py", line 186, in <module>
    from ._noinline import noinline_p
  File "/usr/local/lib/python3.10/dist-packages/equinox/internal/_noinline.py", line 379, in <module>
    jax.core.pp_eqn_rules[noinline_p] = _noinline_pretty_print
  File "/opt/jax/jax/_src/deprecations.py", line 52, in getattr
    raise AttributeError(message)
AttributeError: jax.core.pp_eqn_rules was removed in JAX v0.4.34. `

**Comment by dlwh** [comment]
yeah sorry. we just have to bump equinox

**Comment by dlwh** [comment]
this should be fixed (but I didn't test yet)

**Comment by dlwh** [comment]
this is fixed
